services:
  transformers-notebook:
    image: jupyter/tensorflow-notebook
    ports:
      - "8000:8888"
    environment:
      - JUPYTER_TOKEN=token0

    volumes:
      - ./:/home/asoliman/project/translation-app
